/* dtool_config.h.  Generated automatically by makepanda.py */
#define HAVE_PYTHON 1
#undef PYTHON_FRAMEWORK
#define COMPILE_IN_DEFAULT_FONT 1
#define HAVE_MAYA 1
#undef MAYA_PRE_5_0
#undef HAVE_SOFTIMAGE
#undef SSL_097
#define REPORT_OPENSSL_ERRORS 1
#define HAVE_GL 1
#undef HAVE_MESA
#undef MESA_MGL
#undef HAVE_SGIGL
#undef HAVE_GLX
#define HAVE_WGL 1
#define HAVE_DX 1
#undef HAVE_CHROMIUM
#undef HAVE_THREADS
#undef HAVE_AUDIO
#define NOTIFY_DEBUG 1
#undef DO_PSTATS
#undef DO_COLLISION_RECORDING
#undef TRACK_IN_INTERPRETER
#define DO_MEMORY_USAGE
#undef DO_PIPELINING
#define EXPORT_TEMPLATES yes
#undef LINK_IN_GL
#undef LINK_IN_PHYSICS
#define DEFAULT_PATHSEP ";"
#define DEFAULT_PRC_DIR "<auto>etc"
#define PRC_DIR_ENVVARS "PANDA_PRC_DIR"
#define PRC_PATH_ENVVARS "PANDA_PRC_PATH"
#define PRC_PATTERNS "*.prc"
#define PRC_EXECUTABLE_PATTERNS ""
#define PRC_EXECUTABLE_ARGS_ENVVAR "PANDA_PRC_XARGS"
#define PRC_PUBLIC_KEYS_FILENAME ""
#undef PRC_RESPECT_TRUST_LEVEL
#define PRC_SAVE_DESCRIPTIONS 1
#undef WORDS_BIGENDIAN
#define HAVE_NAMESPACE 1
#undef HAVE_OPEN_MASK
#define HAVE_WCHAR_T 1
#define HAVE_WSTRING 1
#define HAVE_TYPENAME 1
#define SIMPLE_STRUCT_POINTERS 1
#undef HAVE_DINKUM
#undef HAVE_STL_HASH
#undef HAVE_GETTIMEOFDAY
#undef GETTIMEOFDAY_ONE_PARAM
#undef HAVE_GETOPT
#undef HAVE_GETOPT_LONG_ONLY
#undef HAVE_GETOPT_H
#undef IOCTL_TERMINAL_WIDTH
#define HAVE_STREAMSIZE 1
#define HAVE_IOS_TYPEDEFS 1
#define HAVE_IOS_BINARY 1
#define STATIC_INIT_GETENV 1
#undef HAVE_PROC_SELF_EXE
#undef HAVE_PROC_SELF_MAPS
#undef HAVE_PROC_SELF_ENVIRON
#undef HAVE_PROC_SELF_CMDLINE
#define HAVE_GLOBAL_ARGV 1
#undef PROTOTYPE_GLOBAL_ARGV
#define GLOBAL_ARGV __argv
#define GLOBAL_ARGC __argc
#define HAVE_IO_H 1
#define HAVE_IOSTREAM 1
#define HAVE_MALLOC_H 1
#undef HAVE_SYS_MALLOC_H
#undef HAVE_ALLOCA_H
#undef HAVE_LOCALE_H
#define HAVE_MINMAX_H 1
#define HAVE_SSTREAM 1
#define HAVE_NEW 1
#define HAVE_SYS_TYPES_H 1
#undef HAVE_SYS_TIME_H
#undef HAVE_UNISTD_H
#undef HAVE_UTIME_H
#undef HAVE_GLOB_H
#undef HAVE_DIRENT_H
#undef HAVE_SYS_SOUNDCARD_H
#define HAVE_RTTI 1
#undef GLOBAL_OPERATOR_NEW_EXCEPTIONS
#undef OLD_STYLE_ALLOCATOR
#undef GNU_STYLE_ALLOCATOR
#undef VC6_STYLE_ALLOCATOR
#undef MODERN_STYLE_ALLOCATOR
#define NO_STYLE_ALLOCATOR 1
#undef HAVE_ZLIB
#undef HAVE_PNG
#undef HAVE_JPEG
#undef HAVE_TIFF
#undef HAVE_VRPN
#undef HAVE_FMOD
#undef HAVE_NVIDIACG
#undef HAVE_NSPR
#undef HAVE_FREETYPE
#undef HAVE_FFTW
#undef HAVE_SSL
#undef HAVE_NET
#undef HAVE_CG
#undef HAVE_CGGL
